HathorNetwork/hathor-explorer

package.json
src/constants.js
src/screens/Dashboard.js

feat: showing peers qty in statistics screen

---

src/screens/AddressDetail.js

The diff was a bit confusing, so I will describe here the changes.
**The bug**
On `componentDidMount` I was calling `this.setState({ queryParams: this.pagination.obtainQueryParams() })` before the `updateAddress` method but on `componentDidUpdate` I wasn't, so that's the bug (updating the `queryParams` state).
**The fix**
I just moved the state update to the `updateAddress` method.
**Other changes**
- Inside `updateAddress` I am also updating the following states now: `{loadingSummary: true, transactions: []}`. This improves the UI when the address changes.
- Add check for `if (keys.length === 0)` to validate if has any transactions on the searched address.

fix: address search now works when executing a new search

---

src/components/TxData.js

https://github.com/HathorNetwork/hathor-explorer/issues/45
Outputs with unknown script now will look like this:

feat(tx): Show script data when unable to decode

---

src/api/axiosInstance.js
src/api/tokenApi.js
src/components/Navigation.js
src/components/Network.js
src/components/TokenConfig.js
src/components/TokenDetailsTop.js
src/components/TokenDetailsTopNFT.js
src/components/TokenInfo.js
src/components/TokenNFTPreview.js
src/constants.js
src/index.scss
src/screens/TokenDetail.js
src/utils/helpers.js

feat(tx): show media for special tokens

---

src/components/TokenDetailsTop.js
src/components/TokenDetailsTopNFT.js

fix: add margin to boxes on mobile

---

src/components/TokenNFTPreview.js
src/constants.js
src/utils/helpers.js

feat(tx): add NFT audio preview

---

package-lock.json
package.json
src/App.js
src/components/GDPRConsent.js
src/components/TokenNFTPreview.js

Added some explanation here: 
https://github.com/HathorNetwork/internal-issues/issues/29

feat: add cookie consent message

---

src/App.js
src/api/networkApi.js
src/components/Network.js
src/screens/PeerAdmin.js

https://github.com/HathorNetwork/hathor-explorer/issues/73
https://user-images.githubusercontent.com/698586/123879286-0ff32400-d917-11eb-8812-f105d9243d42.mp4

feat(p2p): new network page

---

.github/workflows/deploy.yml
Makefile

closes: https://github.com/HathorNetwork/ops-tools/issues/40

chore: clear cloudfront cache after deploy

---

src/components/TxData.js

Example tx with problem: https://explorer.testnet.hathor.network/transaction/00005f234469407614bf0abedec8f722bb5e534949ad37650f6077c899741ed7

fix: we shouldn't show Spent link on inputs

---

src/api/addressApi.js
src/screens/AddressDetail.js

Use the explorer-service address balance and address search api.

feat: Address Api from explorer-service

---

Makefile
package-lock.json
package.json
src/constants.js

- https://github.com/HathorNetwork/hathor-explorer/pull/151

Release v0.10.3

---

src/App.js
src/components/Navigation.js
src/components/token/TokenRow.js
src/components/token/TokenSearchField.js
src/components/token/Tokens.js
src/components/token/TokensTable.js
src/feature.js
src/index.scss
src/screens/TokenList.js

The following UI components must be created. Real data is not required at this moment:
- Navigation link
- Table
- Components
- Searching/pagination
These are the performed tests (Using mocked data):
https://user-images.githubusercontent.com/3287486/160186605-96a07b05-0606-4643-8948-bf75832a5593.mov
When no Token is found:
https://user-images.githubusercontent.com/3287486/160186719-60dcdc6b-de2d-4649-a0c1-358f684f8118.mov
https://user-images.githubusercontent.com/3287486/160186674-7e5668f5-a2d6-4238-85b6-bb0aeff8e992.mov

feat: create tokens page structure

---

package-lock.json
package.json
src/constants.js

- https://github.com/HathorNetwork/hathor-explorer/pull/178
- https://github.com/HathorNetwork/hathor-explorer/pull/176

bump: v0.10.7

---

src/api/tokensApi.js
src/components/Loading.js
src/components/token/TokenRow.js
src/components/token/TokenSearchField.js
src/components/token/Tokens.js
src/components/token/TokensTable.js
src/index.scss

User must be able to navigate through Tokens page, searching for specific tokens and sorting by fields available on table header.
Consideration:
- After a table header is clicked to sort data, the table will go back to the first page.
- Sort by last column (Type) was not implemented, as only two values are possible (Custom Token or NFT). 
https://user-images.githubusercontent.com/3287486/163101019-2012e3c9-d35b-4bf5-9ed6-8b0bbd6735e4.mov

Retrieve tokens data from explorer-service

---

src/feature.js

This flag was preventing uses to see an unfinished feature. Now that all code was developed and merged, this flag is being set to true.

feat: turn on tokens feature

---

src/feature.js

Temporarily disable tokens feature until we fix token sync on mainnet.

fix: disable tokens feature

---

Makefile
package.json
src/api/tokensApi.js
src/components/ConditionalNavigation.js
src/components/Navigation.js
src/components/error/ErrorMessageWithIcon.js
src/components/token/TokenErrorMessage.js
src/components/token/Tokens.js
src/components/token/TokensTable.js
src/constants.js
src/feature.js
src/index.js
src/screens/TokenList.js

This PR intends to:
1. Add a feature flag to indicate the feature is under maintenance mode.
2. Add a feature flag to turn on/off the navigation bar.
3. Enhance the error handling. New message is presented if status code is different than 200. 
This diagram assumes that Token feature flag is turned on.

feat: enhance tokens feature control and add error handling

---

package-lock.json
package.json
src/constants.js

chore: bump to version v0.12.0

---

package-lock.json
package.json
src/constants.js

chore: bumped to v0.14.0

---

src/screens/AddressDetail.js

- Change legacy unleash flag to latest

feat: use latest instead of legacy

---

package-lock.json
package.json
src/constants.js

chore: bump v0.14.1

---

package-lock.json
package.json
src/constants.js
src/screens/AddressDetail.js

Release v0.14.1

---

src/components/AddressDetailExplorer.js

- Show error message when address has no transacions

feat: show error message for empty addresses

---

package-lock.json
package.json
src/constants.js

chore: bump version v0.14.2

---

package-lock.json
package.json
src/components/AddressDetailExplorer.js
src/components/AddressHistory.js
src/constants.js

Release v0.14.2

---

src/messages.js

feat: add new token/tx ban messages

---

package-lock.json
package.json
src/constants.js

chore: bump to v0.14.3

---

package-lock.json
package.json
src/constants.js

chore: bump v0.15.0

---

package-lock.json
package.json
src/api/addressApi.js
src/components/AddressDetailExplorer.js
src/components/AddressHistory.js
src/components/SortableTable.js
src/constants.js

Release v0.15.0

---

src/api/txApi.js
src/components/Loading.js
src/components/Navigation.js
src/components/tx/TxData.js

- Fix react rendering errors and warnings
- Show error message instead of on screen errors on Decode screen
- Fix PushTx screen

fix: push tx screen

---

package-lock.json
package.json
src/constants.js

chore: bump version v0.15.1

---

package-lock.json
package.json
src/api/txApi.js
src/components/Loading.js
src/components/Navigation.js
src/components/tx/TxData.js
src/constants.js

Release v0.15.1

---

src/App.js
src/api/featureApi.js
src/components/Navigation.js
src/components/feature_activation/FeatureRow.js
src/components/feature_activation/Features.js
src/constants.js
src/index.scss
src/screens/FeatureList.js

- Implement the new Features page as described in https://github.com/HathorNetwork/rfcs/pull/60
Here are a couple of screenshots of the new page (data is faked):

feat(feature-activation): implement features page

---

src/components/Network.js

- Add "Best block: " to selected network peer status (dark gray BG), when `best_block` is available (https://github.com/HathorNetwork/hathor-explorer-service/pull/299 needed, but the explorer should not break without it)
- Add "Protocol:" to show `sync-v1.1` or `sync-v2`, ...
- Correctly calculate the progress on connections using sync-v2 when possible (also needs https://github.com/HathorNetwork/hathor-explorer-service/pull/299)
- Correctly set the state of connections using sync-v2 (also needs https://github.com/HathorNetwork/hathor-explorer-service/pull/299)
- Show "Synced block:" and "Best block:" instead of "Synced timestamp:" and "Latest timestamp" for sync-v2 connections

feat(sync-v2): support showing protocol version and sync-v2 info

---

package-lock.json
package.json
src/constants.js

- Bump version from v0.16.0 to v0.17.0

chore: bump version v0.17.0

---

package-lock.json
package.json
src/constants.js

chore: bump package to v0.18.0

---

src/components/token/TokenBalanceRow.js

- Update prettyValue usage from old lib.

fix: update usage of helpers from old lib version

---

package-lock.json
package.json
src/constants.js

chore: bump v0.18.1

---

package-lock.json
package.json
src/components/tx/TxData.js
src/constants.js

Release v0.18.1

---

src/App.js
src/components/tx/TxData.js

feat: add new poablock fields

---

package-lock.json
package.json
src/App.js
src/actions/index.js
src/components/AddressDetailExplorer.js
src/components/AddressDetailLegacy.js
src/components/token/TokenAutoCompleteField.js
src/components/token/TokenBalances.js
src/components/tx/TxData.js
src/constants.js
src/reducers/index.js

- Remove uses of HATHOR_TOKEN_CONFIG
- Remove all hardcoded mentions of HTR
- Use the native token configured by the fullnode (or use HTR as default)

feat: native token config

---

package-lock.json
package.json
src/constants.js

chore: bump v0.19.0

---

package-lock.json
package.json
src/constants.js

- Bump package version to v0.19.1

chore: bump package version to v0.19.1

---

package-lock.json
package.json
src/api/axiosInstance.js
src/components/Navigation.js
src/constants.js

Release v0.19.1

---

src/components/tx/TxData.js

- Show list of actions of a nano contract tx in the Tx detail screen
Note: do not consider the wrong address parse and arguments from the images, consider only the actions.

feat: show the list of actions of a nano contract tx in the tx data screen

---

.eslintrc.js
.prettierrc
package-lock.json
package.json

- Adds linting and formatting dev dependencies to the project
- Adds configuration for linting and formatting
The rules included were the ones that were recently agreed upon by https://github.com/HathorNetwork/hathor-wallet-lib/pull/669 , only adapted to a javascript-only web project.
Since the lint/format dependencies also had to be included on the project now, and this generates a lot of reviewable changes, this PR will not actually change any code and will not modify the CI.

feat: Adds eslint configs and deps

---

package-lock.json
package.json
src/components/tx/TxData.js
src/screens/nano/NanoContractDetail.js

A [new PR](https://github.com/HathorNetwork/nano-hathor-core/pull/71) from nano hathor core will return the specific custom field for each nano transaction argument. With this improvement, we can show formatted arguments to improve UX/UI.
- Format nano arguments with custom types better in the transaction detail and nano detail screens.

feat: format nano custom types to improve UX/UI

---

package-lock.json
package.json
src/constants.js

chore: bump explorer to v0.20.0

---

package-lock.json
package.json
src/constants.js

- https://github.com/HathorNetwork/hathor-explorer/pull/307

bump: v0.20.1

---

src/screens/DecodeTx.js

- Refactors DecodeTx screen to funcitonal component

refactor: DecodeTx to functional component

---

src/screens/Dashboard.js

- Refactors the Statistics page to functional component

chore: Statistics to functional component

---

src/screens/BlockList.js
src/screens/TransactionList.js

- Refactors "BlockList" screen to functional components
- Refactors "TransactionList" screen to functional components

Refactor: Transaction list screens

---

src/screens/TokenDetail.js

- Refactors Token Details screen to functional component

Refactor: Token details to functional component

---

src/screens/PushTx.js

- Refactors the Push Tx screen to functional component

refactor: PushTx to functional component

---

src/screens/VersionError.js

- Refactors Version Error screen to functional components

Refactor: Version screen to functional

---

package-lock.json
package.json
src/constants.js

- Bumps the Explorer to patch version `0.20.2`

Chore: Bump v0.20.2

---

package-lock.json
package.json
src/App.js
src/api/addressApiLegacy.js
src/api/graphvizApi.js
src/api/metadataApi.js
src/api/nanoApi.js
src/api/networkApi.js
src/api/tokenApi.js
src/api/txApi.js
src/api/version.js
src/components/Navigation.js
src/components/token/TokenBalanceRow.js
src/components/token/TokenRow.js
src/components/tx/TxRow.js
src/constants.js
src/screens/AddressDetail.js
src/screens/BlockList.js
src/screens/Dag.js
src/screens/Dashboard.js
src/screens/DecodeTx.js
src/screens/PeerAdmin.js
src/screens/PushTx.js
src/screens/TokenDetail.js
src/screens/TransactionDetail.js
src/screens/TransactionList.js
src/screens/VersionError.js

- #299
- #300
- #301
- #302 
- #310 
- #311 
- #312 
- #313 
- #314 
- #315 
- #318 
- #316 
- #320

Release: v0.20.2

---

package-lock.json
package.json
src/constants.js

chore: bump v0.20.3

---

package-lock.json
package.json
scripts/deploy.sh
src/constants.js
src/screens/nano/BlueprintDetail.js
src/screens/nano/NanoContractDetail.js

Release v0.20.3

---

package-lock.json
package.json
src/constants.js

chore: bump v0.20.4

---

scripts/deploy.sh

- Re-add the GTM id. It was accidentally removed in https://github.com/HathorNetwork/hathor-explorer/pull/274

fix: missing GTM id

---

package-lock.json
package.json
src/constants.js

- Include here all things that this PR should solve

bump: v0.20.5

---

src/components/AddressHistory.js

- Fixes a minor bug that caused the address history not to show

fix: Address history not showing

---

package-lock.json
package.json

- Bumps application version to `0.21.0`

chore: bump v0.21.0

---

src/newUi.scss

- This PR includes the fix revamp of the following components:
- Navigation
- Correcting the color of the entire text in the search input
[Vídeo 12-18 às 16.50.webm](https://github.com/user-attachments/assets/436d17a4-72c8-4e87-8221-b8d9ef64fe7f)
[Gravação-20241218_164942.webm](https://github.com/user-attachments/assets/99a3cf09-b9f0-4bdd-ac5e-ce909698f620)

fix: revamp mobile search input on light mode

---

src/newUi.scss

- Include fix tooltip response.
[Vídeo 12-18 às 16.46 (1).webm](https://github.com/user-attachments/assets/714492fc-34bb-4268-9476-457224aa006a)
[Vídeo 12-18 às 16.46.webm](https://github.com/user-attachments/assets/79bf85a5-030d-46bd-9801-79c3c69c3536)

FIX:  Tooltip Mobile Token Details

---

src/screens/TokenDetail.js

-  Including pagination in token details.
[Vídeo 20-12 às 10. 09.webm](https://github.com/user-attachments/assets/bacaace0-cbac-462d-9b55-91a6f38d4e22)

fix: Including pagination in token details.

---

src/components/tx/TxData.js

- Including parentheses in the number of actions
[Vídeo 20-12 às 10. 09.webm](https://github.com/user-attachments/assets/6a2bad59-a83e-4daf-9511-019ef1de671d)

fix: revamp amount of actions with parenthesis

---

src/App.js
src/newUi.scss

- Fixing the page footer at the bottom of the screen
[Vídeo 20-12 às 10. 09.webm](https://github.com/user-attachments/assets/5ba807c8-6345-4fa7-8ae2-0fb75c7ae702)

fix: footer at the bottom of the screen

---

src/components/token/TokenInfo.js
src/newUi.scss

- Fixing canMint validation in TokenDetail
- Now the "CAN MINT NEW TOKENS" field receives false if the token object's mint is an empty array, and true otherwise.
[Vídeo 12-19 às 15.24 (1).webm](https://github.com/user-attachments/assets/13d2e8c5-d7ca-492e-b898-14aead069b3f)

Fix: revamp can mint tokens

---

src/components/feature_activation/Features.js
src/newUi.scss

- Adjusting text alignment in Column Description
[Vídeo 20-12 às 10. 09 (1).webm](https://github.com/user-attachments/assets/1325f5a3-bf57-42ae-b4f6-0de02819b353)

fix: revamp text alignment feature details

---

src/newUi.scss

- Adjusting text properties in the Token Details screen
[Vídeo 12-24 às 9.59.webm](https://github.com/user-attachments/assets/03d41a92-a4e2-4897-a24f-14dd94de2f89)

Fix: Revamp Sizes and bold amounts on Token Details

---

src/components/Network.js

- Adjusting progress bar borders in network screen
[Vídeo 12-26 às 9.59 (1).webm](https://github.com/user-attachments/assets/05ab7155-8ad4-4916-8e0c-c75e2a302593)
[Vídeo 12-26 às 9.59.webm](https://github.com/user-attachments/assets/8ec25dc0-7165-41b5-a2f8-99fbacf87d63)

fix: revamp network synchronization bars

---

src/newUi.scss

- Adjusting z-index of selectbox in the Address Details screen.
[Vídeo 12-26 às 9.59 (2).webm](https://github.com/user-attachments/assets/f7e4a9dc-b1c5-436c-b489-c7f05705b5cf)

Fix: Revamp Token selectbox behind other visual elements

---

src/components/tx/TxData.js

- Fixing the text of txdata to bold.
[Vídeo 20-12 às 10. 09 (2).webm](https://github.com/user-attachments/assets/1f25e0d1-762a-4b50-91a7-b131978aad27)

fix: revamp txdata text bold

---

src/App.js
src/newUi.scss

- Setting max-width for screens larger than 1920x1080.
[Vídeo 12-23 às 10.59 (4).webm](https://github.com/user-attachments/assets/94796c65-bb5d-4223-a019-b16a7a35fbe9)

fix: revamp max width 1920x1080

---

package-lock.json
package.json

chore: Bump to v0.21.2 patch

---

.stylelintrc.json
package-lock.json
package.json
src/App.js
src/components/Navigation.js
src/components/Network.js
src/components/NewHathorAlert.js
src/components/feature_activation/Features.js
src/components/token/TokenInfo.js
src/components/tx/TxData.js
src/index.scss
src/newUi.scss
src/screens/Dashboard.js
src/screens/DecodeTx.js
src/screens/TokenDetail.js
src/screens/TransactionDetail.js

- Releases vesion `0.21.2` into public testnet

[0.21.2] Merge `master` into `release`

---

src/components/Footer.js
src/components/Navigation.js
src/components/Sidebar.js
src/newUi.scss

We are cleaning some information from the navigation so we can better add the nano menu in the next PR.
Figma: https://www.figma.com/design/IeP1TlJ2rPyGQBWxE4Al0f/Explorer?node-id=2304-32043&t=d5v5j2mvqRVidMk5-0
- The network must be moved below the hathor logo and without the prefix "Hathor".
- The box explorer should be moved to the footer.
- The mobile sidebar should be more clean.
- Increase search bar size (this wasn't on figma but it was too small. Maybe this will be reduced when nano navigation is added)

feat: improvements for the navigation and footer

---

src/App.js
src/api/nanoApi.js
src/components/Navigation.js
src/components/Sidebar.js
src/components/nano/NanoContractsTable.js
src/constants.js
src/newUi.scss
src/screens/nano/NanoContractsList.js

- Add nano contracts list
- Show nano contract menu only if the server connected has nano contract enabled
https://github.com/user-attachments/assets/a9603b30-0c51-489f-8060-96a91ad350a2
https://github.com/user-attachments/assets/308107e2-c09d-400a-b9d2-84a53a02a731

feat: add nano contracts list

---

package-lock.json
package.json

- Include here all things that this PR should solve

chore: bump to v0.22.0

---

package-lock.json

- Solves https://github.com/advisories/GHSA-968p-4wvh-cqc8

chore(deps): Upgrades babel helpers

---

src/components/tx/TxData.js

- Add a link to blueprint details for ocb tx details screen.

Add ocb link to details

---

.github/workflows/deploy.yml
scripts/deploy.sh

- Make sure we deploy to the new nano-testnet hackaton

chore: nano-testnet hackaton

---

package-lock.json
package.json

chore: Bump to v0.23.0

---

package-lock.json
package.json
src/components/tx/TxData.js

- Upgrade wallet-lib to 2.5.1
- Update nano tx parser typing

Update nano tx parser typing

---

.github/workflows/deploy.yml
Makefile
scripts/deploy.sh

- Allow deploys to nano-testnet bravo
- Disable deploys to nano-testnet alpha

chore: nano-testnet-bravo

---

.github/workflows/deploy.yml
scripts/deploy.sh

- Merge master changes into release

fix: nano-alpha deploy (#419)

---

package-lock.json
package.json

Chore/bump v0.24.1

---

package-lock.json
package.json
src/api/txApi.js

- bump wallet-lib
- use tx api schemas to validate api responses

fix: validate tx api response

---

package-lock.json
package.json

chore: bump v0.24.2

---

package-lock.json
package.json
src/api/txApi.js

- sync release v0.24.2 with master branch

sync: release v0.24.2

---

.github/workflows/deploy.yml
scripts/deploy.sh

- Allow deploys to the new testnet-hotel

chore: testnet hotel
