HathorNetwork/hathor-explorer

- src/App.js
- src/components/Navigation.js
- src/components/TxData.js
- src/screens/Dashboard.js
- src/screens/TokensList.js
Closes #16 
- Add block height on Transaction Detail screen;
- Remov `toString()` to nonce, so screen is not broken for merged mined blocks anymore;
- Now it shows 'Merged mined block' as type on Transaction Detail screen;
- Add height of the best chain on Statistics screen;
- Add tokens list screen with navigation link to it.
> Improvements on UI using new APIs

- package-lock.json
- package.json
- src/components/Transactions.js
This change adds URL history support (shareable URLs, back/forward browser support, etc.) to pages displaying transaction history.
**Affected Pages**
All pages displaying transaction history:
* [Blocks](https://explorer.hathor.network/blocks/)
* [Transactions](https://explorer.hathor.network/transactions/)
* [Token Detail](https://explorer.hathor.network/token_detail/00000eaee9f22c832b2b3affc71ce8ab2254957723557d0679dbbdc8a7fcdf4f)
**User Experience**
No UX change on the initial view of those pages. As the user navigates the transaction history using paging buttons Next/Previous, the URL parameters are added and updated accordingly. When the user gets back to the most recent page, the URL parameters are removed.
The introduced URL parameters maps 1:1 with the arguments of the [underlying …
> feat: URL history on transaction list browsing

- Makefile
Minor fix in the build script for testnet, which was using a wrong env var name
> fix: testnet build

- src/components/TxData.js
There are some transactions that have many inputs/outputs and would be great to easily know how many of them we have.
Old screen:
New screen:
1
OR 
2
> feat: show quantity of transaction inputs and outputs in transaction detail screen

- src/screens/Dashboard.js
Integers values should be formatted with thousand separator in Statistics screen.
> feat: format statistics values with thousand separator

- package-lock.json
- package.json
- src/components/tx/TxData.js
- Output script data shouldn't show 'unable to decode' anymore, so any NFT creation tx will show the decoded script data.
- Bump wallet lib version after release
Old screen
New screen
> feat: decode output script data in the tx detail screen

- Makefile
> fix: testnet fullnode url and s3 bucket

- Makefile
- src/components/token/TokenNFTPreview.js
Many ipfs files don't have extension, so the explorer failed to show the preview for videos and audios in this situation.
Reference issue: https://github.com/HathorNetwork/hathor-nft-review/issues/56
The explorer must support a new optional field in the tokens metadata `mime_type`, e.g. video/mp4, image/png, application/pdf, .... We use this field in the client to set the media source instead of using extension, which is limited. This is better than having the content type only (mp4, mp3, ...) because we can directly use it to render the media in the client.
Note:
I've updated the testnet URL in the Makefile to use `node1.testnet.` instead of `node1.golf.testnet`, so we don't need to update it every new testnet release.
> feat: we must support using an optional field in the token metadata: content_type

- src/screens/Dashboard.js
To give a better user experience on statistics page, we are removing "Blocks" line and renaming "Height of the best chain" to "Blocks (best height)".
The Explorer must render the statistics page as this screenshot:
> feat(statistics): remove 'Blocks' and rename 'Height of the best chain' info (#159)

- src/components/tx/TxData.js
- src/index.scss
- src/screens/DecodeTx.js
- src/screens/TransactionDetail.js
Today, when the user loads the transaction page, it automatically loads the neighbors graphs (verification and funds). If the user opens many transactions, the interface starts to slow down because of these automatically loaded graphs.
To solve this problem, a lazy loading mechanism was introduced. Now, the graph will only be loaded when user requests.
User must be able to visualize neighbors graphs when clicking on "Click to show" and hiding it clicking on "Click to hide", as shown on this video:
Obs. A sleep of 5 seconds was intentionally placed to simulate a scenario where the full-node is taking too long to respond:
https://user-images.githubusercontent.com/3287486/151799933-a3af6eeb-df32-428d-acdb-cf4c9a6f3513.mov
> feat(transactions): load neighbors graphs only when requested by user (#158)

- Makefile
- We should use the new `node-explorer` that was created in the Testnet.
> chore: use new testnet fullnode

- src/components/token/Tokens.js
Every query made on tokens page must generate a query string (Even the query that is made when user first access the page).
Example: ```/tokens?searchText=tes1&sortBy=uid&order=asc```
> feat: add querystring to tokens page

- src/components/token/TokenAutoCompleteField.js
- src/components/token/TokenBalances.js
- Address list must have the selected token in the query params, so we can share the link with it.
https://user-images.githubusercontent.com/3298774/173409762-a0ae4f97-cc0a-4d58-9b9f-f3689a1108cc.mov
- We must make it more clear that when there is nothing in the search, then we are showing the address list for HTR
This one is a bit tricky because the best approach would be to have HTR as a search element just like any other token. However, this would require much more changes in the code, then I feel this change is good enough for now with a simple UI change.
> feat: add token to the query params in the address list screen

- src/index.scss
Increase timeseries iframe height. So, at least for desktop, the iframe scrollbar does not appear, making the experience smoother.
https://user-images.githubusercontent.com/3287486/176070932-2ed12fd9-35d0-408b-8040-51fa385941f2.mov
> fix: change timeseries iframe height

- src/api/tokensApi.js
- src/components/token/TokenBalances.js
- We should use the new fetch token API from the explorer-service to retrieve the hathor token transactions count
- We should use the `transactions` column from the token entry retrieved from the search to display the total number of transactions for a given token
- If the fetch token API request fails, we should hide the information
> refactor: using transactions count from the token entry instead of the tokenInformation API

- src/components/AddressDetailExplorer.js
- src/components/AddressHistory.js
When searching for another address, sometimes the page is not set on the querystring and `+query.page` which would convert the page to a number returns `NaN`.
This makes a couple methods which expect a number to fail and not load the page properly.
- Use the default page 1 when the querystring parameter `page` is not set.
> fix: page NaN on querystring changes

- src/api/addressApi.js
- src/components/AddressDetailExplorer.js
- src/components/AddressHistory.js
- src/components/SortableTable.js
This PR is part of the https://github.com/HathorNetwork/internal-issues/issues/131 design
- We should replace the pages pagination with a `next` and `previous` button
- We should fetch data from the new paginated tx history API
> refactor: address tx history pagination

- src/api/featureApi.js
- src/components/feature_activation/FeatureDataRow.js
- src/components/feature_activation/FeatureRow.js
- src/components/feature_activation/SignalBitRow.js
- src/components/tx/TxData.js
- src/utils/featureActivation.js
Depends on https://github.com/HathorNetwork/hathor-explorer/pull/242
- Move `getPrettyState()` to utils file
- Implement the new signal bits table in the Block page as described in the [RFC](https://github.com/HathorNetwork/rfcs/blob/master/projects/feature-activation/0003-explorer-uis.md)
Here's an image of the new implemented block page:
> feat(feature-activation): implement blocks page

- src/components/feature_activation/FeatureRow.js
- src/components/feature_activation/Features.js
- Improve UI of feature activation screen showing thousand separator for height values
Old screen
New screen
> feat: improve feature activation UI with thousand separator for height values

- src/components/tx/TxData.js
A beta tester was testing a blueprint that has a method without arguments. A transaction with this method was throwing an error in the frontend because the arguments were `null`. I also improved the UI for an empty list.
- We should show a single dash (-) when a nano contract transaction has no arguments in the Transaction Detail screen.
> fix: nc arguments might be null or an empty array, so we must handle it properly

- src/components/Navigation.js
- Only show tokens tab if at least one of its options are enabled
All items under the tokens tab are protected behind an unleash feature flag, but if all feature flags are disabled the UI would show an empty dropdown
To prevent this, we need to remove the tokens tab altogether when all feature flags are disabled.
For reference, when all items are enabled we have this:
Ideally we should have a component to conditionally render the tab, but using unleash's `useFlag` on callbacks and not on the component body directly would fail building the explorer.
Later we can refactor this with a custom hook to check multiple flags, but since this is the only instance where this behavior is required we can use conditional rendering without any code repetition.
> feat: hide tokens tab

- package-lock.json
- package.json
- src/App.js
- src/actions/index.js
- src/components/AddressDetailExplorer.js
- src/components/AddressDetailLegacy.js
- src/components/AddressHistory.js
- src/components/AddressHistoryLegacy.js
- src/components/AddressSummary.js
- src/components/AddressSummaryLegacy.js
- src/components/Navigation.js
- src/components/Network.js
- src/components/feature_activation/FeatureRow.js
- src/components/feature_activation/Features.js
- src/components/timeseries/ScreenStatusMessage.js
- src/components/token/TokenAutoCompleteField.js
- src/components/token/TokenBalanceRow.js
- src/components/token/TokenBalances.js
- src/components/token/TokenInfo.js
- src/components/tx/TxData.js
- src/constants.js
- src/reducers/index.js
- src/screens/Dashboard.js
- src/utils/helpers.js
> Release v0.19.0

- src/api/axiosInstance.js
- src/components/Navigation.js
1. `TypeError: axios.create is not a function`
It's still unclear why this stopped working in this release but using `import` instead of `require` fixes the bug. https://github.com/HathorNetwork/hathor-explorer/commit/8cabe6fa73f17043dc6d21d25666d6687ef03792
2. hooks can only be called inside of the body of a function component. 
The method `useFlag` can't be used inside of class component. https://github.com/HathorNetwork/hathor-explorer/commit/34f4e6faca16868ce0a8f5b98e452e5d18874c1c
- Use `import` instead of `require` for axios.
- Refactor `Navigation` component to a function.
> fix v0.19.0 deploy bugs

- package-lock.json
- package.json
- src/constants.js
- src/index.js
- React Router should be upgraded to the latest `v5`
- React root should be initialized in [the v18 way](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis), complementing #283 
- Minor code cleanup
> feat: Upgrades router to v5

- src/screens/nano/NanoContractDetail.js
- Show list of balances of a nano contract in the Nano contract detail screen
> feat: show balances of tokens of a nano contract

- .github/workflows/deploy.yml
- .github/workflows/pr-validation.yml
- Makefile
- scripts/deploy.sh
- Use https://github.com/aws-actions/configure-aws-credentials to get temporary AWS Credentials for the job, instead of using permanent credentials stored in Github. The roles that will be assumed by Github Actions for this are being created in https://github.com/HathorNetwork/ops-tools/pull/871
- Add steps to deploy to our alternative testnets every time we deploy to the main one
- Refactor the Makefile so it uses a bash script for the deploy logic
> ci: deploy to sub-accounts

- src/api/nanoApi.js
- src/components/nano/NanoContractHistory.js
- src/constants.js
- src/screens/nano/NanoContractDetail.js
- Add pagination to the table of a nano contract history
https://github.com/user-attachments/assets/abdeeafe-ca5a-44e2-a0d4-34309e0f90c9
https://github.com/HathorNetwork/hathor-explorer-service/pull/331
https://github.com/HathorNetwork/nano-hathor-core/pull/95
> feat: add list pagination to the nano contract history table

- package-lock.json
- package.json
- src/api/nanoApi.js
- src/index.js
- src/index.scss
- src/screens/nano/BlueprintDetail.js
- We must show the blueprint source code in the blueprint detail screen.
Note I: I decided to install a package to highlight the code because the UI is improved a lot, the package is extensively used, and the explorer is not a code as critical as the wallet in terms of handling sensitive data.
Note II: it needs a new API in the nano hathor core (https://github.com/HathorNetwork/nano-hathor-core/pull/96) and the corresponding API in the explorer service (https://github.com/HathorNetwork/hathor-explorer-service/pull/333)
https://github.com/user-attachments/assets/77dbd9af-08da-4fea-990e-b94f0c719e2a
> feat: add blueprint code to the blueprint detail screen

- .eslintrc.js
- src/api/addressApi.js
- src/api/addressApiLegacy.js
- src/api/axiosInstance.js
- src/api/customAxiosInstance.js
- src/api/metadataApi.js
- src/components/DagComponent.js
- src/components/Network.js
- src/components/Version.js
- src/index.js
- src/screens/FeatureList.js
- src/utils/date.js
- src/utils/helpers.js
- Fix all lint warnings and errors on this application
- The only exception is the parsing error found on most screens: that will only be solved by migrating them to functional components
> style: Manual lint fixes

- package-lock.json
- package.json
- src/components/AddressHistory.js
- src/components/AddressHistoryLegacy.js
- src/components/Navigation.js
- src/components/Network.js
- src/components/SortableTable.js
- src/components/feature_activation/FeatureDataRow.js
- src/components/feature_activation/FeatureRow.js
- src/components/feature_activation/Features.js
- src/components/token/TokenAlerts.js
- src/components/token/TokenAutoCompleteField.js
- src/components/token/TokenBalanceRow.js
- src/components/token/TokenConfig.js
- src/components/token/TokenMarkers.js
- src/components/token/TokenRow.js
- src/components/token/TokenSearchField.js
- src/components/tx/Transactions.js
- src/components/tx/TxAlerts.js
- src/components/tx/TxData.js
- src/components/tx/TxMarkers.js
- src/components/tx/TxRow.js
- src/index.scss
- src/screens/Dag.js
- The Bootstrap framework should be upgraded from v4 to v5 ( [changes](https://getbootstrap.com/docs/5.0/migration/) )
- There should be a minimum of visual changes
A quick visualization of the visual changes can be seen on the video below.
The tab with the green margins is the one with Bootstrap 5 running on developer localhost, while the one without the border is the existing Bootstrap 4 running on public testnet.
[Screencast from 20-08-2024 20:19:50.webm](https://github.com/user-attachments/assets/8c63203a-3be9-4ff8-bb25-fd936d4f4524)
> chore: Upgrade Bootstrap from v4 to v5

- QA.md
- Add QA steps for nano screens
> chore: add QA steps for nano screens

- .github/workflows/deploy.yml
- We should stop getting the error we had in https://github.com/HathorNetwork/hathor-explorer/actions/runs/10619060179/job/29435812404
This is another one I triggered with the fix showing that it could go past the steps that was erroring: https://github.com/HathorNetwork/hathor-explorer/actions/runs/10619740019/job/29438015637
> fix: upgrade download-artifact action version to fix error

- src/WebSocketHandler.js
- Fixes linting issues on the websocket file that were causing `Parse errors` on the arrow functions
- Adds a warning to help identify if the `ws://` protocol is being incorrectly used instead of `wss://`, which is helpful after the changes on #274
> fix: Websocket linting and error warning

- src/screens/TransactionDetail.js
- Refactors the `TransactionDetail` screen to a functional component
Just like what happened with #296 , despite the logic staying the same, this code was changed a lot. This makes the `diff` hard to read. The best way to review this screen is to open the [before](https://github.com/HathorNetwork/hathor-explorer/commit/b61769d6a6395dbc5c96f5f3c2a462107b693048) and [after](https://github.com/HathorNetwork/hathor-explorer/blob/1dab0a84c350143376398d135517f9938fb71f72/src/screens/TransactionDetail.js) to look at the changes.
> refactor: TransactionDetail.js to functional component

- src/api/addressApiLegacy.js
- src/api/graphvizApi.js
- src/api/metadataApi.js
- src/api/nanoApi.js
- src/api/networkApi.js
- src/api/tokenApi.js
- src/api/txApi.js
- src/api/version.js
- The default error handlers for our APIs should also handle errors not related to Axios
- Handlers that were expected to only output to console should do so
> fix: Default error handling on api helpers

- src/screens/TransactionDetail.js
On #297 a bug was implemented that added the Transaction metadata into the wrong state property.  This PR fixes this mistake with the expected behavior of [the previous iteration](https://github.com/HathorNetwork/hathor-explorer/blob/b61769d6a6395dbc5c96f5f3c2a462107b693048/src/screens/TransactionDetail.js#L101) of this screen.
- Correctly updates the transaction metadata with the response from the Explorer Service
> Fix: Transaction detail metadata

- src/App.js
- src/components/Navigation.js
- src/components/token/TokenBalanceRow.js
- src/components/token/TokenRow.js
- src/components/tx/TxRow.js
- src/screens/PeerAdmin.js
- Refactors the Row components to functional components
- Improves the memoization of `useSelector` on the root screen
- Minor fixes on route-related parameter passing for the `Navigation` and `PeerAdmin` screens
These components use the `withRouter` element that is deprecated and will be unavailable on Router v6. So we need to refactor them while on Router v5.
The memoization improvement was suggested for the `TokenBalanceRow` and I decided to implement it on the root screen as well, since it's so simple.
> refactor: Row components to functional

- src/screens/AddressDetail.js
A similar quick-fix as the one made by #316, this is a quick fix that precedes the refactoring that will be implemented by #317 and #319
- The children of the `AddressDetail` screen should receive the correct parameters
> Fix: Address detail params

- src/screens/DecodeTx.js
https://github.com/HathorNetwork/hathor-explorer/issues/331
The decode-tx API does not return `success: False` when the decoding fails, that's why the current code has a bug.
- The error message should be correctly shown when decoding an invalid tx.
> fix: show error message when decode tx fails

- src/components/AddressDetailExplorer.js
- Refactors the AddressDetailExplorer to functional component
This component used the deprecated [`withRouter` connector](https://v5.reactrouter.com/web/api/withRouter), which will become unavailable in the coming upgrade to React Router v6.
In order to remove its usage, it was necessary to refactor it to use react hooks as a functional component. This proved to be harder than initially foreseen because the code relied heavily upon async state setters, a feature that is also no longer available with `useState()` hooks.
So, instead of setting the state, waiting for it to be rendered and then applying the next set of instructions, the code now sets the state and then a `useEffect()` handles its change. Many data flow reorganizations were made to achieve this new structure.
Since this …
> refactor: AddressDetailExplorer to fn component

- src/components/token/TokenBalances.js
- The `TokenBalances` component should be refactored to functional component
As with the other recent functional component rewritings, it's easier to review by comparing the [before](https://github.com/HathorNetwork/hathor-explorer/blob/b61769d6a6395dbc5c96f5f3c2a462107b693048/src/components/token/TokenBalances.js) and [after](https://github.com/HathorNetwork/hathor-explorer/blob/48f504f9582458551633564a28c9198dc89af03b/src/components/token/TokenBalances.js) than by looking at the diff directly.
> Refactor: Token balances to fn component

- .eslintrc.js
- .github/workflows/pr-validation.yml
- src/components/AddressDetailLegacy.js
- src/components/AddressHistory.js
- src/components/AddressHistoryLegacy.js
- src/components/AddressSummary.js
- src/components/AddressSummaryLegacy.js
- src/components/feature_activation/Features.js
- src/components/timeseries/ScreenStatusMessage.js
- src/components/token/TokenAutoCompleteField.js
- src/components/token/Tokens.js
- src/components/tx/TxData.js
- Wraps up the work started by #291 and #294
- Fixes a parsing error that was preventing lint from running on all the modified files in this PR
- Implements all automatic lint fixes for those files
- Implements all manual lint fixes for those files
The `prettier` fixes were already implemented, as the parsing problem was only happening for Eslint.
> Fix: Eslint parsing

- package-lock.json
- package.json
- src/constants.js
- We're doing this bump directly to `master` because there has been an error in https://github.com/HathorNetwork/hathor-explorer/pull/337, which was merged to `master` instead of `dev`.
- We want to release only the commit that went directly to `master` this time, so it made sense to bump on it
- After this release, we will merge the `master` back into `dev` to make sure it gets the 2 commits (the change and the bump)
> bump: v0.20.6

- scripts/check_version
- src/constants.js
- All code paths that require the version number should fetch if from the `package.json` directly
- The `check_version` script should validate both application version numbers from the lockfile
> refactor: centralize version number on package

- src/components/DagComponent.js
- src/components/DropDetails.js
- src/components/GDPRConsent.js
- src/components/NewHathorAlert.js
- src/components/feature_activation/FeatureRow.js
- src/components/feature_activation/Features.js
- src/components/tx/TxData.js
- src/components/tx/TxTextInput.js
- src/newUi.scss
- src/screens/Dag.js
- src/screens/DecodeTx.js
- src/screens/FeatureList.js
- src/screens/PushTx.js
- This PR includes the revamp of the following screens:
- Decode TX
- Push TX
- DAG
- Features
- The `GDPRConsent` cookie alert has been fixed.
[DecodeTX.webm](https://github.com/user-attachments/assets/8938d3fc-7256-45a0-85d0-9df62505ac52)
[DecodeTXMobile.webm](https://github.com/user-attachments/assets/cd656c8d-65cf-4cb5-9972-499aa1d55954)
[PushTX.webm](https://github.com/user-attachments/assets/74d40b6a-7955-4502-8f6a-ea1a05fc72d4)
[PushTXMobile.webm](https://github.com/user-attachments/assets/fbd754d7-51e8-4068-a7d7-32107042b6c0)
[DAG.webm](https://github.com/user-attachments/assets/815e3d36-5ad4-4e50-8ad7-2d90b4ac7c1b)
[DAGMobile.webm](https://github.com/user-attachments/assets/f560eca3-a418-4a0e-b918-16a4fcde319a)
[Feature.webm](https://github.com/user-attachments/assets/f140fc96-8db …
> feat: revamp-tools-ui

- src/components/Navigation.js
- src/components/NewHathorAlert.js
- src/newUi.scss
When the user tries to use the search box with the new UI and inputs invalid data ( ex.: an address from another network ), the app throws a javascript error that the `ref` does not exist.
This was solved by providing an error handler for the Navigation element, with the same fixed positioning as the current UI. Screenshots below for reference.
- The correct error message is shown when the search box has invalid content
> [!WARNING]
> The PR indicates there are hundreds of changed lines. This happened because I needed to add one indentation to the Navigation file. To avoid confusion on the review proccess, I recommend activating the **Hide Whitespaces** feature on the files tab.
> That way only the actual changes are displayed, and not the hundreds of indentation changes.
> fix: Error handling on nav search for new UI

- package-lock.json
- package.json
- src/newUi.scss
Some visual elements were not being displayed. Upon investigation, it was found that the reason was an invalid value of `0px` on opacity fields. In development environment this problem did not occur, as the SCSS interpreter was being less strict.
Those elements were removed.
- Fixes all instances of visual elements not being displayed
- Bumps version to patch `0.21.1`, as the release process is not fully implemented in this repository #343
> Fix: Invalid opacity value

- .stylelintrc.json
- package-lock.json
- package.json
- src/index.scss
- src/newUi.scss
With the new UI, the complexity of our CSS has increased and we had some hard-to-detect styling errors on our last release process ( see #356 ).
By adding a dedicated lint dependency ( [Stylelint](https://stylelint.io/) ) we increase the automated scrutinity of our code and improve its overall quality.
- Adds the Stylelint dependency with its [default ruleset](https://stylelint.io/user-guide/rules) of over 100 rules
- Apply all automated changes from `lint:scss:fix`
The final goal of this dependency is to be added to the CI itself. However, it will require many PRs with smaller, peer reviewable changes to reach that point.
Until then, it's the developer responsibility to run the linter before merging the new feature PRs.
> Feat: Add css linting

- src/newUi.scss
- Adjusting font weight under the button in Decode and Push Tx
[Vídeo 12-24 às 9.59.webm](https://github.com/user-attachments/assets/dd1a669e-a6e5-4667-880a-843c5ce25532)
> fix: revamp "Decode" and "Push Tx" texts under the button are too bold

- src/newUi.scss
- src/screens/Dashboard.js
In the new interface, the timer does not update when the number of txs or the blocks height change. An example of the timer is as follows:
A new version of this screen has changed the counter to the title element, instead of inside each of the realtime boxes, as follows:
- The seconds counter should be updated only when the best block height changes
The current implementation is still not precise, because the `time` property of the `dashboard:metrics` websocket event received has no relation to the best block or transaction data.
This screen should rely on the information received through the websocket as it is now, but the server-side implementation of this event should be changed in the future to provide more precise information here.
> fix: Statistics seconds counter

- src/components/Navigation.js
- src/components/NewHathorAlert.js
- src/newUi.scss
During some tests where many components were being clicked in short sequence, the `NewHathorAlert` component could break by being unable to manipulate the dom correctly: the expected element would already be unmounted when the timer finished.
Also, the alert container for fixed positioning, used in the Navigation search, was overlaying the screen elements, preventing clicks on the application elements.
- The new alert component should not break under race conditions
- The new alert component should not prevent click in any screen elements
> fix: Alert unmount and overlay

- package-lock.json
- package.json
- src/App.js
- src/components/AddressDetailExplorer.js
- src/components/AddressDetailLegacy.js
- src/components/ConditionalNavigation.js
- src/components/Navigation.js
- src/components/Network.js
- src/components/Sidebar.js
- src/components/token/TokenBalanceRow.js
- src/components/token/TokenBalances.js
- src/components/token/TokenRow.js
- src/components/token/Tokens.js
- src/components/tx/TxRow.js
- src/screens/AddressDetail.js
- src/screens/PeerAdmin.js
- src/screens/TokenList.js
This PR upgrades the React Router from version `5.x` to `v6`. Below are the guides followed to implement the necessary adaptations:
- [Migration guide](https://reactrouter.com/en/main/upgrading/v5) from v5 to v6
- Similar upgrade on the Desktop Wallet repository: https://github.com/HathorNetwork/hathor-wallet/pull/555
- Continues the upgrade started on #289
- Upgrades the React Router to the latest stable version v6
- Most of the file changes were due to renaming all instances of `useHistory` to `useNavigate` on the screens.
- For a smaller scope and easier reviewing, the available [future proofing flags](https://reactrouter.com/6.29.0/upgrading/future) will not be implemented in this PR, despite being available at the current version.
> feat: Upgrades `react-router` to `v6`

- src/App.js
- src/api/nanoApi.js
- src/components/AddressHistory.js
- src/components/EllipsiCell.js
- src/components/Navigation.js
- src/components/Sidebar.js
- src/components/SortableTable.js
- src/components/nano/BuiltInBlueprintsTable.js
- src/components/nano/OnChainBlueprintsTable.js
- src/components/token/TokenBalanceRow.js
- src/components/token/TokenRow.js
- src/components/token/TokensTable.js
- src/components/tx/TxRow.js
- src/constants.js
- src/newUi.scss
- src/screens/nano/BlueprintList.js
- src/utils/pagination.js
- Add new Navigation for nano
- Add blueprint list with two tabs (on chain and built in)
- Refactor EllipsisCell component to receive the elements count as props because now we have different counts depending on the component
- Fix missing arrow in sorting header for Tokens table
https://github.com/user-attachments/assets/482e3010-a03c-4050-93ac-e655f9603c94
https://github.com/user-attachments/assets/1fab628f-7f16-4d43-a784-44f58079c499
> feat: add blueprint list

- src/components/AddressDetailExplorer.js
- src/components/AddressHistory.js
A bug was happening when the `AddressHistory` screen was shown, as the `isMobile` hook was being called inside a class component. Hook calls are only allowed inside functional components.
The hook usage was moved to a parent component and passed as a prop to the AddressHistory.
- AddressHistory screen shows properly
> fix: hook usage on AddressHistory

- .github/workflows/deploy.yml
The `4.0.2` version of the `actions` GitHub action we've been using for the last months ( since #279 ) has been disabled by some reason that still needs to be understood.
Since we were pinning the version directly to [the commit hash `0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`](https://github.com/actions/cache/commit/0c45773b623bea8c8e75f6c82b208c3cf94ea4f9), the deploy command suddenly stopped working when the [tag `4.0.2`](https://github.com/actions/cache/releases/tag/v4.0.2) somehow ceased to be available. Re-running the workflow did not work, even though both the tag and commit are still available through the links above. 
An issue to understand this change will be opened to further investigate, since all other actions in this repository workflow use hash-locked versions. But for this …
> fix: deploy action version

- config-overrides.js
We were having errors when trying to load the "Transaction Details" screen for a nano contract tx. This was happening because the module for Axios was not being found by the browser, and instead if was being fed only a string containing the module path.
A fix had to be implemented in the `config-override.js` file to instruct WebPack v5 on where to find the module, which is in a file format we did not configure previously on the CRA upgrade ( #386 ).
- The "Nano Contract Overview" section of a nc transaction should be exhibited on the "Transaction Details" screen
> fix: `cjs` file handling for axios

- src/components/token/TokenDetailsTop.js
- src/newUi.scss
- NFTs display should show as third column on desktops, each taking 1/3 of the space.
- When it's not an NFT, display just two sections, each taking 50% of the space ([example](https://explorer.hathor.network/token_detail/000001139655b68f6adbff6f0fc164d2164a2905868f13ed04382a55b26374fe)).
- On mobile, token sections should be one under the other.
Currently: https://explorer.hathor.network/token_detail/000000005f7095d4f0180b2238d7a9f7113c115de4b001eef3aef04289d08a5e
Fixed:
> fix: display NFTs token info in three columns
